version: '3'

networks:
    lamp-network:
    
services:
    web-server:
        build: ./webserver
        ports: 
            - "80:80"
        volumes:
            - ./app:/var/www/html
        links:
            - db-server
        networks:
            - lamp-network
    
    db-server:
        image: mysql:8.0
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: 12345678
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - lamp-network
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db-server:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: 12345678 
        networks:
            - lamp-network
volumes:
    persistent: